import type {
  Reporter,
  FullConfig,
  Suite,
  TestCase,
  TestResult,
  FullResult,
} from "@playwright/test/reporter";
import fs from "fs";
import path from "path";
import archiver from "archiver";
import { sendEmail } from "../utils/emailSender";

export default class EmailReporter implements Reporter {
  private startTime!: number;
  private endTime!: number;

  private total = 0;
  private passed = 0;
  private failed = 0;
  private skipped = 0;

  onBegin(config: FullConfig, suite: Suite) {
    this.startTime = Date.now();
    this.total = suite.allTests().length;
  }

  onTestEnd(test: TestCase, result: TestResult) {
    if (result.status === "passed") this.passed++;
    else if (result.status === "failed") this.failed++;
    else if (result.status === "skipped") this.skipped++;
  }

  async onEnd(result: FullResult) {
    this.endTime = Date.now();
    const duration = ((this.endTime - this.startTime) / 1000).toFixed(2);

    const isFailed = this.failed > 0;
    const statusText = isFailed ? "FAILED ❌" : "PASSED ✔";
    const bannerColor = isFailed ? "#b71c1c" : "#1b5e20";
    const subject = `Playwright Automation Report — ${isFailed ? "FAILED" : "PASSED"}`;

    // 🔹 ZIP playwright-report folder
    const zipPath = await this.zipPlaywrightReport();

    // 🔹 Build rich HTML email
    const html = `
<div style="font-family: Segoe UI, Arial; max-width: 900px; margin: auto;">

  <div style="background:${bannerColor}; color:white; padding:14px; font-size:18px; font-weight:bold;">
    Playwright Automation Report — ${statusText}
  </div>

  <h3>📊 Execution Summary</h3>
  <table border="1" cellpadding="10" cellspacing="0" style="border-collapse:collapse;">
    <tr style="background:#f2f2f2;">
      <th>Total</th><th>Passed</th><th>Failed</th><th>Skipped</th><th>Duration</th>
    </tr>
    <tr align="center">
      <td>${this.total}</td>
      <td style="color:green;"><b>${this.passed}</b></td>
      <td style="color:red;"><b>${this.failed}</b></td>
      <td>${this.skipped}</td>
      <td>${duration} sec</td>
    </tr>
  </table>

  <h3>🧪 Validated Scope</h3>
  <ul>
    <li>Authentication using storage state</li>
    <li>Eligibility CSV file import</li>
    <li>Import summary & eligibility validation</li>
    <li>Pending Processing record validation</li>
  </ul>

  ${
    isFailed
      ? `
  <h3 style="color:#b71c1c;">❌ Failure Detected</h3>
  <p>
    One or more tests failed.<br/>
    Please <b>download and extract</b> the attached
    <b>playwright-report.zip</b>, then open
    <code>index.html</code> to view:
  </p>
  <ul>
    <li>Step-by-step execution</li>
    <li>Error stack traces</li>
    <li>Screenshots & videos</li>
    <li>Trace viewer</li>
  </ul>
  `
      : `
  <h3 style="color:#1b5e20;">✅ No Failures</h3>
  <p>All tests passed successfully.</p>
  `
  }

  <h3>📎 Artifacts</h3>
  <ul>
    <li>✔ Full Playwright HTML report (ZIP)</li>
    <li>✔ Screenshots, videos, traces (on failure)</li>
  </ul>

  <hr />
  <p style="font-size:12px; color:#555;">
    Generated by Playwright Automation Framework
  </p>
</div>
`;

    const attachments: string[] = [];
    if (zipPath) attachments.push(zipPath);

    await sendEmail(subject, "Playwright automation execution report", attachments, html);
  }

  // 🔧 Helper: ZIP playwright-report folder
 private async zipPlaywrightReport(): Promise<string | null> {
  const reportDir = path.join(process.cwd(), "playwright-report");
  
  if (!fs.existsSync(reportDir)) return null;

  const zipPath = path.join(process.cwd(), "playwright-report.zip");

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 9 } });

    output.on("close", () => resolve(zipPath));
    archive.on("error", err => reject(err));

    archive.pipe(output);
    archive.directory(reportDir, false);
    archive.finalize();
  });
}

}
