import fs from 'fs';
import path from 'path';

export interface User {
  username: string;
  password: string;
}

/**
 * Loads the list of test users from data/users.json.
 * Passwords are never logged.
 * Throws a clear error if the file is missing or malformed.
 */
export function getUsers(): User[] {
  const usersFilePath = path.resolve(__dirname, '../data/users.json');

  try {
    const rawData = fs.readFileSync(usersFilePath, 'utf-8');
    const users: User[] = JSON.parse(rawData);

    if (!Array.isArray(users) || users.length === 0) {
      throw new Error('users.json is empty or not an array.');
    }

    console.log(`Loaded ${users.length} user(s) from users.json`);
    return users;
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new Error('users.json contains invalid JSON. Check the file format.');
    }
    throw new Error(
      `Unable to load users.json from "${usersFilePath}". ` +
      'Ensure the file exists locally or is generated by the CI workflow. ' +
      `Details: ${(error as Error).message}`
    );
  }
}
